services:
  indexer:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.1
    container_name: indexer
    volumes:
      - ./index2_data:/usr/share/elasticsearch/data
    environment:
      discovery.type: "single-node"
      ES_JAVA_OPTS: "-Xms2048m -Xmx2048m"

  service:
    image: ghcr.io/knaw-huc/ineo_service:latest
    container_name: service
    ports:
      - "8000:8000"
    depends_on:
      - indexer
    environment:
        ELASTICSEARCH_HOST: "indexer"
        ELASTICSEARCH_PORT: 9200
        ELASTICSEARCH_INDEX: "ineo"
        FRONTEND_HOST: "http://localhost:3000"
    volumes:
      - ./data:/data

  ineo:
    image: ghcr.io/knaw-huc/ineo_frontend:latest
    container_name: ineo
    ports:
      - "3000:80"
    depends_on:
      - service
      - indexer
