volumes:
  index2_data:
  service-data:
  wpdb_data:
  wp-content:

networks:
  traefik-public:
    external: true

services:
#  indexer:
#    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.1
#    container_name: indexer
#    restart: unless-stopped
#    networks:
#      - traefik-public
#    volumes:
#      - index2_data:/usr/share/elasticsearch/data
#    environment:
#      discovery.type: "single-node"
#      ES_JAVA_OPTS: "-Xms2048m -Xmx2048m"

  service:
    image: ghcr.io/knaw-huc/ineo_service:0.5
    container_name: service
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.service.rule=Host(`ineo-service.sd.di.huc.knaw.nl`)"
      - "traefik.http.routers.service.entrypoints=http"
      - "traefik.http.services.service.loadbalancer.server.port=8000"
    networks:
      - traefik-public
    environment:
      ELASTICSEARCH_SCHEME: ${ELASTICSEARCH_SCHEME}
      ELASTICSEARCH_HOST: ${ELASTICSEARCH_HOST}
      ELASTICSEARCH_PORT: ${ELASTICSEARCH_PORT}
      ELASTICSEARCH_INDEX: ${ELASTICSEARCH_INDEX}
      ELASTICSEARCH_USERNAME: ${ELASTICSEARCH_USERNAME}
      ELASTICSEARCH_PASSWORD: ${ELASTICSEARCH_PASSWORD}
      FRONTEND_HOST: ${FRONTEND_HOST}
    volumes:
      - service-data:/data
